import express from "express";
import OpenAI from "openai";
const app=express(); app.use(express.json({limit:"64kb"}));
const PORT=process.env.PORT||3000, SHOP=process.env.SHOPIFY_STORE_DOMAIN||"hogparts.com";
const TOKEN=process.env.SHOPIFY_STOREFRONT_TOKEN, KEY=process.env.OPENAI_API_KEY, MODEL=process.env.OPENAI_MODEL||"gpt-5-mini";
const SYSTEM=`You work on the sales counter at Hogparts UK Ltd. Talk to the customer like a normal helpful person in a motorcycle parts shop. Use British English. Be warm, concise and confident when the catalogue has a confirmed answer. Never mention catalogue evidence, verification, candidate data, server checks, search logic, confidence, Shopify, handles or internal systems. Never narrate how you reached the answer. Never use markdown symbols such as **, ### or backticks. Do not repeat the customer's whole question back to them. Never invent fitment, stock, specifications, prices or delivery information. When verified matches are supplied, they fit: simply tell the customer what you have and the useful differences. Product name, SKU and price are useful. If there are organic and sintered pads, explain the difference in one short sentence and ask which they prefer. Only ask for more bike details when there are no verified matches and those details would genuinely help.`;
async function sf(query,variables={}){if(!TOKEN)throw Error("Shopify Storefront token not configured");const r=await fetch(`https://${SHOP}/api/2026-07/graphql.json`,{method:"POST",headers:{"Content-Type":"application/json","Shopify-Storefront-Private-Token":TOKEN},body:JSON.stringify({query,variables})});const j=await r.json();if(!r.ok||j.errors)throw Error(j.errors?.map(e=>e.message).join("; ")||`Shopify request failed: ${r.status}`);return j.data}
const PQ=`query Search($q:String!){products(first:25,query:$q){nodes{id handle title vendor productType description tags featuredImage{url altText} variants(first:3){nodes{id title sku price{amount currencyCode} availableForSale}} fitment:metafield(namespace:"custom",key:"fitment"){value} specifications:metafield(namespace:"custom",key:"specifications"){value}}}}`;
async function one(q){return (await sf(PQ,{q})).products.nodes}
function uniq(arr){const m=new Map();for(const p of arr)m.set(p.id,p);return [...m.values()]}
function score(p,t){const s=(p.title+" "+p.productType+" "+p.description+" "+(p.tags||[]).join(" ")).toLowerCase();let n=0;for(const x of [t.part,t.modelCode,t.model,String(t.year||"")])if(x&&s.includes(String(x).toLowerCase()))n+=x===t.part?6:4;if(t.position&&s.includes(t.position.toLowerCase()))n+=2;return n}
async function interpret(client,message){const r=await client.responses.create({model:MODEL,instructions:"Extract a motorcycle-parts shopping query. Return ONLY compact JSON with keys part, year, make, model, modelCode, family, position. Use null when unknown. Example: front brake pads for a 2020 Low Rider FXLR => part brake pads, year 2020, model Low Rider, modelCode FXLR, family Softail, position front.",input:message});try{return JSON.parse(r.output_text)}catch{return {part:message}}}
function partQueries(t){const p=String(t.part||"").trim();const qs=[p];if(/brake\\s*pads?/i.test(p))qs.push('"brake pad"','tag:"Product Name_Brake Pad"',"brake pads");if(t.position&&p)qs.push(`${t.position} ${p}`);return [...new Set(qs.filter(Boolean))]}
function fitmentLine(p,t){const d=(p.description||"")+" "+(p.fitment?.value||"");const code=String(t.modelCode||"").trim().toLowerCase();if(!code)return "";const chunks=d.split(/(?=Harley[- ]Davidson|INDIAN|BUELL|Part Numbers)/i);return chunks.find(x=>x.toLowerCase().includes(" "+code+" "))||""}
function yearCovered(line,year){if(!year)return true;const y=Number(year);const re=/(19|20)\\d{2}(?:\\s*-\\s*((?:19|20)\\d{2}))?/g;let m;while((m=re.exec(line))){const a=Number(m[0].slice(0,4)),b=m[2]?Number(m[2]):a;if(y>=a&&y<=b)return true}return false}
function positionMatches(p,t){if(!t.position)return true;const spec=(p.description||"").split(/Fitment/i)[0].toLowerCase();const pos=String(t.position).toLowerCase();return spec.includes("mounting position : "+pos)||spec.includes("mounting position: "+pos)}
function exactEvidence(p,t){const line=fitmentLine(p,t);return !!line&&yearCovered(line,t.year)&&positionMatches(p,t)}
async function retrieve(t,message){let batches=await Promise.all(partQueries(t).map(q=>one(q).catch(()=>[])));let pool=uniq(batches.flat());let exact=pool.filter(p=>exactEvidence(p,t));if(exact.length<4){const extra=[];if(t.modelCode)extra.push(t.modelCode);if(t.model)extra.push(t.model);if(t.year&&t.part)extra.push(`${t.part} ${t.year}`);const more=await Promise.all(extra.map(q=>one(q).catch(()=>[])));pool=uniq(pool.concat(more.flat()));exact=pool.filter(p=>exactEvidence(p,t))}return (exact.length?exact:pool).map(p=>({p,s:score(p,t)})).sort((a,b)=>b.s-a.s).slice(0,20).map(x=>x.p)}
app.get("/health",(_q,r)=>r.json({ok:true,shop:SHOP,aiConfigured:!!KEY,shopifyConfigured:!!TOKEN}));
app.post("/api/chat",async(req,res)=>{try{if(!KEY)return res.status(503).json({error:"AI is not configured yet"});const message=String(req.body?.message||"").trim();if(!message)return res.status(400).json({error:"Message required"});const client=new OpenAI({apiKey:KEY});const intent=await interpret(client,message);const products=await retrieve(intent,message);const catalogue=products.map(p=>({title:p.title,handle:p.handle,vendor:p.vendor,productType:p.productType,tags:p.tags,description:p.description,fitment:p.fitment?.value||"",specifications:p.specifications?.value||"",variants:p.variants.nodes.map(v=>({sku:v.sku,price:v.price,availableForSale:v.availableForSale}))}));const confirmed=products.filter(p=>exactEvidence(p,intent));
let answer;
if(confirmed.length){
 const opts=confirmed.map(p=>{const sku=p.variants.nodes[0]?.sku||"";const price=p.variants.nodes[0]?.price;const title=p.title.replace(/\s+for Harley-Davidson.*$/i,"").replace(/Harley\/buell/ig,"").trim();const type=/organic/i.test(p.description||p.title)?"organic":/sintered/i.test(p.description||p.title)?"sintered":"";return {title,sku,price,type}});
 const seen=new Set(), clean=opts.filter(o=>{const k=o.sku||o.title;if(seen.has(k))return false;seen.add(k);return true});
 const bike=[intent.year,intent.model||intent.modelCode].filter(Boolean).join(" ");
 const lines=clean.map(o=>{const pr=o.price?.amount?" - £"+Number(o.price.amount).toFixed(2):"";return (o.type?o.type[0].toUpperCase()+o.type.slice(1)+" - ":"")+o.title+(o.sku?" (SKU "+o.sku+")":"")+pr});
 answer="Yes, we've got "+(intent.position?intent.position+" ":"")+(intent.part||"parts")+" for your "+bike+".\n\n"+lines.join("\n");
 const types=new Set(clean.map(o=>o.type).filter(Boolean));
 if(types.has("sintered")&&types.has("organic"))answer+="\n\nThe sintered pads give stronger braking and generally last longer, while the organic pads have a softer initial feel. Which would you prefer?";
 else if(clean.length>1)answer+="\n\nWould you like me to help you choose between them?";
} else {
 const response=await client.responses.create({model:MODEL,instructions:SYSTEM,input:`Customer question: ${message}\nParsed bike/part: ${JSON.stringify(intent)}\nNo server-confirmed product match was found. Respond naturally and briefly. Ask for only the single most useful missing detail if it could help.`});
 answer=response.output_text;
}res.json({answer,intent,products:products.slice(0,6).map(p=>({title:p.title,handle:p.handle,image:p.featuredImage?.url||null,url:`https://hogparts.com/products/${p.handle}`}))})}catch(e){console.error(e);res.status(500).json({error:e.message})}});
app.get("/",(_q,res)=>res.type("html").send(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Hogparts AI Assistant</title><style>body{font:16px Arial,sans-serif;max-width:800px;margin:50px auto;padding:20px;background:#f5f5f5}.box{background:#fff;padding:24px;border-radius:12px}input{width:75%;padding:12px}button{padding:12px}#out{white-space:pre-wrap;margin-top:20px}</style></head><body><div class="box"><h1>Hogparts AI Assistant</h1><p>Development test interface. Not connected to the live storefront.</p><input id="q" placeholder="Ask about a product or fitment"><button onclick="go()">Ask</button><div id="out"></div></div><script>async function go(){let o=document.getElementById("out");o.textContent="Thinking...";let r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:document.getElementById("q").value})});let j=await r.json();o.textContent=j.answer||j.error||"No response"}</script></body></html>`));
app.listen(PORT,()=>console.log(`Hogparts AI Assistant v0.8 listening on ${PORT}`));
